
sudo: required

# Enable C++ support
language: c

# Compiler selection
compiler:
  - gcc

before_install:
  - cd ..
  - git clone --recursive https://github.com/espressif/esp-idf.git esp-idf
  - cd esp-idf && git checkout --recurse-submodules tags/v3.2.3
  - cd ..
  - export IDF_PATH=/home/travis/build/cmbahadir/esp-idf
  - sudo apt-get install gcc git wget make libncurses-dev flex bison gperf python python-pip python-setuptools python-serial python-pyparsing
  - python -m pip install --user -r $IDF_PATH/requirements.txt 
  - mkdir esp && cd esp
  - wget https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
  - tar -xzf xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
  - export PATH="/home/travis/build/cmbahadir/esp/xtensa-esp32-elf/bin:$PATH" && cd .. 
  - mv opcua-esp32 $IDF_PATH/examples

# Build steps
script:
  - cd $IDF_PATH/examples/opcua-esp32
  - rm -r components/tcpip_adapter components/lwip components/freertos
  - cp -r $IDF_PATH/components/tcpip_adapter components/ && cp -r $IDF_PATH/components/lwip components/ && cp -r $IDF_PATH/components/freertos components/ 
  - make